name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]  # Set this to the node version you are using

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install test dependencies
        run: npm install --only=dev


    - name: Build
      run: npm run build  # Replace with your actual build script

    - name: Run unit tests
      run: npm test

    - name: Run integration tests
      run: npm run test:integration  # Replace with your actual script for integration tests

    - name: Generate code coverage report
      run: npm run coverage  # Replace with your actual script to generate the code coverage

    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Required only for private repositories
        files: ./coverage/lcov.info  # Adjust the path according to your coverage report location
        flags: unittests  # Optional, and can be used to differentiate coverage reports for different tests

    - name: Launch application
      run: npm run start  # Replace with your actual script to start the application

    - name: Execute end-to-end tests
      run: npm run test:e2e  # Replace with your actual script for e2e tests
