name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.16.0'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Run Unit Tests
      run: npm run test -unit.test.js 
    - name: Run Integration Tests
      run: npm run test -integration.test.js 
    - name: Start Application
      run: npm start &
    - name: Run End-to-End Tests
      run: npx playwright test 
    - name: Generate Coverage Report
      run: npm run test -- --coverage
    - name: Upload code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code coverage report
        path: test
